DROP DATABASE IF EXISTS ID_STORE;
DROP USER IF EXISTS ID_STOREU@localhost;

CREATE DATABASE ID_STORE;

USE ID_STORE;

CREATE TABLE USERS (
    ID int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR (45) NOT NULL UNIQUE,
    JASYPT_PASS VARCHAR (100),
    LAST_LOGON TIMESTAMP NULL DEFAULT NULL,
    IS_LOCKED bit(1) NOT NULL DEFAULT 0,
    CREATED_AT TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    UPDATED_AT TIMESTAMP(0) NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP(0),
    PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX USERS_ID_INDEX ON USERS (ID);
CREATE UNIQUE INDEX USERS_USERNAME_INDEX ON USERS (USERNAME);

-- Table denormalized to support the "JDBC Realm" interface
-- Also, not a bad idea to trade space for performance
CREATE TABLE `GROUPS` (
    ID int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    GROUPNAME VARCHAR (45) NOT NULL,
    USERID int(10) UNSIGNED NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT fk_grp_usr FOREIGN KEY (USERID) REFERENCES USERS (id)
);

CREATE INDEX GROUPS_USERID_INDEX ON `GROUPS` (USERID);
CREATE INDEX GROUPS_GROUPNAME_INDEX ON `GROUPS` (GROUPNAME);

CREATE USER ID_STOREU@localhost IDENTIFIED BY 'Deutsche Sprache, schwere Sprache!';
GRANT SELECT ON ID_STORE.* TO ID_STOREU@localhost;
GRANT UPDATE (LAST_LOGON) ON ID_STORE.USERS TO ID_STOREU@localhost;
FLUSH PRIVILEGES;

START TRANSACTION;

INSERT INTO `users`(USERNAME, JASYPT_PASS) VALUES ('sadeq', 'sz/GmYUoX+qI/A/VPxxEmiijzRiwg+2Wtosab7Tvv8OcWXg0Tm6AUJ5iujLfQ2sS');
INSERT INTO `users`(USERNAME, JASYPT_PASS, IS_LOCKED) VALUES ('ali', 'KFbAcO6O82iWnNkatTfpCV4x/6TAm1tfrmlci/rN8T4lrDYiYkSse+zz9+feohGC', 1);
INSERT INTO `users`(USERNAME, JASYPT_PASS) VALUES ('reza', 'Q88uUA85acVdutovyhe750TKzcWTHUMjgv1Xr3I9omQyX3Znz5hZV8el5U3a1PDn');
INSERT INTO `users`(USERNAME, JASYPT_PASS) VALUES ('hossein', 'RGJ1Dc2b4SlYCo1/0BWfJkT6iz/Qw4ermdC7zgU9Mbt35aqeWwVEGi6cNRkHV+LT');
INSERT INTO `users`(USERNAME, JASYPT_PASS) VALUES ('gholi', 'i3Tv/LcdzFI38wGKKfJHsEoND64gTJOBGgBW/evHdSwuWERGldqA9+KW8JNJu9WP');
INSERT INTO `users`(USERNAME, JASYPT_PASS) VALUES ('kambiz', '0VAPKKryqcRpBmfXevMOMJoonmjM6vMRuFuiXxZ1Mlj3gkB+xFWG9kCspSx4BGw0');


INSERT INTO `groups`(GROUPNAME, USERID) VALUES ('admins', 1);
INSERT INTO `groups`(GROUPNAME, USERID) VALUES ('users', 1);
INSERT INTO `groups`(GROUPNAME, USERID) VALUES ('users', 2);
INSERT INTO `groups`(GROUPNAME, USERID) VALUES ('users', 4);
INSERT INTO `groups`(GROUPNAME, USERID) VALUES ('guests', 5);

COMMIT;